create table person(
                       user_id int generated by default as identity primary key,
                       username varchar not null,
                       age int check ( age > 0 ),
                       card varchar,
                       password varchar not null,
                       wallet int,
                       role varchar
);
create table cinema(
                       cinema_center_id int generated by default as identity primary key,
                       name varchar not null
);
create table movies(
                       movie_id int generated by default as identity primary key ,
                       movie_name varchar not null ,
                       description varchar not null ,
                       genre varchar not null,
                       inwhattimestart date,
                       inwhattimeend date,
                       availableplace int not null,
                       price int,
                       raiting double precision,
                       duration double precision,
                       cinema_center_id int references cinema(cinema_center_id) on delete cascade
);

create table comment(
                        comment_id int generated by default as identity primary key ,
                        comment varchar,
                        rating int,
                        created_at date,
                        movie_id int references movies(movie_id) on delete cascade ,
                        user_id int references person(user_id) on delete cascade
);
create table transaction_history(
    transaction_id int generated by default as identity primary key,
    total_price int,
    created_at date,
    user_id int references person(user_id) on delete cascade,
    movie_id int references movies(movie_id) on delete cascade,
    cinema_id int references cinema(cinema_center_id) on delete cascade
)